### ISSUE TITLE
Integrating Laravel with React

### ISSUE THREAD

**Issue by onyijne** [BuildForSDG/Phenom-Backend#3]
**Information needed to serve as guide**
A brief research on using Laravel(Lumen) with React would be helpful as a guide to us while building our solution.

**What information do we need**
We need information on technical guides, what will work best and any known challenge and how to fix it if any.

**Comment by uchennaibekwe** [comment]
Here is important info from the Lumen documentation:

> Lumen 5.2 represents a shift on slimming Lumen to focus solely on serving stateless, JSON APIs. **As such, sessions and views are no longer included with the framework.** If you need access to these features, you should use the full Laravel framework.

So, since we intend to use Lumen to just create an API for the backend, then we can go ahead and work with it instead of the full Laravel. Lumen also promises speed, so it is faster than Laravel itself.

We can always refer to [the lumen document](https://lumen.laravel.com/docs/7.x) for all the help we may need along the line.

With React, we can consume the API from our Lumen micro-framework. So, React would be used the usual way to achieve the consumption of APIs

**Comment by onyijne** [comment]
@uchennaibekwe so we should stick with Lumen?

**Comment by onyijne** [comment]
Okay @uchennaibekwe thanks. Please help us with [setting up Lumen](https://github.com/BuildForSDG/Phenom-Backend/issues/2)
